In [1]:
import duckdb
import pandas as pd
import os

In [2]:
df_epci = pd.read_csv("../data/processed/epci_membres.csv")

In [3]:
query = """
SELECT 
    siren,
    sum(superficie_km2) AS superficie_km2
FROM df_epci
GROUP BY siren
"""

df_surface_epci = duckdb.sql(query)
df_surface_epci

┌───────────┬────────────────┐
│   siren   │ superficie_km2 │
│   int64   │     double     │
├───────────┼────────────────┤
│ 200029999 │          170.0 │
│ 200042497 │          182.0 │
│ 200042935 │          601.0 │
│ 200069193 │          635.0 │
│ 200070555 │          213.0 │
│ 200071751 │         1208.0 │
│ 240100610 │          127.0 │
│ 240100891 │          173.0 │
│ 200040426 │          330.0 │
│ 200043495 │          309.0 │
│     ·     │             ·  │
│     ·     │             ·  │
│     ·     │             ·  │
│ 249500109 │           88.0 │
│ 249500513 │          200.0 │
│ 200041507 │          209.0 │
│ 249710070 │          342.0 │
│ 200027548 │        11920.0 │
│ 249740077 │          377.0 │
│ 249740085 │          564.0 │
│ 249740101 │          535.0 │
│ 200050532 │           10.0 │
│ 200060457 │           80.0 │
├───────────┴────────────────┤
│    1267 rows (20 shown)    │
└────────────────────────────┘

In [4]:
df_cat_nat = pd.read_csv("../data/data_cat_nat/raw/catnat_gaspar.csv",sep=';')
df_cat_nat

,cod_nat_catnat,cod_commune,lib_commune,num_risque_jo,lib_risque_jo,dat_deb,dat_fin,dat_pub_arrete,dat_pub_jo,dat_maj
0,BUDD8750027A,06120,Saint-Étienne-de-Tinée,GLT,Glissement de Terrain,1985-01-01,1986-12-31,1987-05-20,1987-05-24,2022-05-20 15:53:47.090
1,BUDD8750038A,2B050,Calvi,ICB,Inondations et/ou Coulées de Boue,1987-01-14,1987-01-15,1987-06-24,1987-07-10,2022-05-20 15:53:47.111
2,BUDD8750038A,30006,Aimargues,ICB,Inondations et/ou Coulées de Boue,1987-02-11,1987-02-13,1987-06-24,1987-07-10,2022-05-20 15:53:47.138
3,BUDD8750038A,30020,Aubord,ICB,Inondations et/ou Coulées de Boue,1987-02-11,1987-02-13,1987-06-24,1987-07-10,2022-05-20 15:53:47.138
4,BUDD8750038A,30033,Beauvoisin,ICB,Inondations et/ou Coulées de Boue,1987-02-11,1987-02-13,1987-06-24,1987-07-10,2022-05-20 15:53:47.138
...,...,...,...,...,...,...,...,...,...,...
260794,IOME2219351,12013,Aubin,ICB,Inondations et/ou Coulées de Boue,2022-06-04 02:00:00,2022-06-04 02:00:00,2022-07-09 02:00:00,2022-07-22 02:00:00,2022-09-30 02:00:00
260795,INTE2217496A,03110,Espinasse-Vozelle,ICB,Inondations et/ou Coulées de Boue,2022-06-03 02:00:00,2022-06-05 02:00:00,2022-06-15 02:00:00,2022-07-02 02:00:00,2022-09-30 02:00:00
260796,IOME2219351,53145,Marigné-Peuton,ICB,Inondations et/ou Coulées de Boue,2022-05-20 02:00:00,2022-05-20 02:00:00,2022-07-09 02:00:00,2022-07-22 02:00:00,2022-09-30 02:00:00
260797,INTE2217496A,22210,Ploubazlanec,ICB,Inondations et/ou Coulées de Boue,2022-06-03 02:00:00,2022-06-05 02:00:00,2022-06-15 02:00:00,2022-07-02 02:00:00,2022-09-30 02:00:00
260798,IOME2219351,53152,Meslay-du-Maine,ICB,Inondations et/ou Coulées de Boue,2022-05-20 02:00:00,2022-05-20 02:00:00,2022-07-09 02:00:00,2022-07-22 02:00:00,2022-09-30 02:00:00

In [9]:
df_cat_nat[df_cat_nat["cod_commune"].str.startswith("691")]

,cod_nat_catnat,cod_commune,lib_commune,num_risque_jo,lib_risque_jo,dat_deb,dat_fin,dat_pub_arrete,dat_pub_jo,dat_maj
229,BUDD8750068A,69105,Lacenas,ICB,Inondations et/ou Coulées de Boue,1987-06-15,1987-06-15,1987-09-27,1987-10-09,2022-05-20 15:53:47.748
1089,ECOA8800079A,69108,Lancié,ICB,Inondations et/ou Coulées de Boue,1988-05-13,1988-05-14,1988-10-07,1988-10-23,2022-05-20 15:55:10.706
1867,ECOA880100A,69143,Neuville-sur-Saône,ICB,Inondations et/ou Coulées de Boue,1988-05-15,1988-05-15,1989-01-05,1989-01-14,2022-05-20 15:55:12.507
2467,INTE0000045A,69116,Limonest,ICB,Inondations et/ou Coulées de Boue,1999-10-22,1999-10-24,2000-02-07,2000-02-26,2022-05-24 11:23:50.692
2468,INTE0000045A,69123,Lyon,ICB,Inondations et/ou Coulées de Boue,1999-10-22,1999-10-24,2000-02-07,2000-02-26,2022-05-24 11:23:50.692
...,...,...,...,...,...,...,...,...,...,...
259122,NOR19821118,69122,Lucenay,ICB,Inondations et/ou Coulées de Boue,1982-11-06 01:00:00,1982-11-10 01:00:00,1982-11-18 01:00:00,1982-11-19 01:00:00,2022-05-20 02:00:00
259323,NOR19821118,69186,Saint-Clément-de-Vers,TMP,Tempête,1982-11-06 01:00:00,1982-11-10 01:00:00,1982-11-18 01:00:00,1982-11-19 01:00:00,2022-05-20 02:00:00
259324,NOR19821118,69186,Saint-Clément-de-Vers,ICB,Inondations et/ou Coulées de Boue,1982-11-06 01:00:00,1982-11-10 01:00:00,1982-11-18 01:00:00,1982-11-19 01:00:00,2022-05-20 02:00:00
259653,NOR19821118,69154,Pollionnay,ICB,Inondations et/ou Coulées de Boue,1982-11-06 01:00:00,1982-11-10 01:00:00,1982-11-18 01:00:00,1982-11-19 01:00:00,2022-05-20 02:00:00
259654,NOR19821118,69154,Pollionnay,TMP,Tempête,1982-11-06 01:00:00,1982-11-10 01:00:00,1982-11-18 01:00:00,1982-11-19 01:00:00,2022-05-20 02:00:00

In [5]:
query = """ 
SELECT 
    count(dat_pub_arrete) AS nb_cat_nat,
    siren,
    epci_nom,
    dept_epci
FROM df_epci
LEFT JOIN df_cat_nat 
ON df_epci.code_insee = df_cat_nat.cod_commune
GROUP BY siren, epci_nom, dept_epci
ORDER BY siren
"""

duckdb.sql(query).df()

,nb_cat_nat,siren,epci_nom,dept_epci
0,22,75056,Paris,75
1,58,200000172,CC Faucigny - Glières,74
2,46,200000438,CC du Pays de Pontchâteau St-Gildas-des-Bois,44
3,31,200000545,CC des Portes de Romilly sur Seine,10
4,86,200000628,CC Rhône Lez Provence,84
...,...,...,...,...
1262,144,249740077,CA CIVIS (Communauté Intercommunale des Villes...,974
1263,83,249740085,CA du Sud,974
1264,110,249740093,CA Intercommunale de la Réunion Est (CIREST),974
1265,92,249740101,CA Territoire de la Côte Ouest (TCO),974
1266,80,249740119,CA Intercommunale du Nord de la Réunion (CINOR),974

In [3]:
df_cat_nat['lib_risque_jo'].unique()

array(['Glissement de Terrain', 'Inondations et/ou Coulées de Boue',
       'Mouvement de Terrain', 'Avalanche', 'Secousse Sismique',
       'Inondations Remontée Nappe',
       "Chocs Mécaniques liés à l'action des Vagues",
       'Effondrement et/ou Affaisement',
       'Eboulement et/ou Chute de Blocs', 'Sécheresse',
       'Vents Cycloniques', 'Raz de Marée', 'Lave Torrentielle',
       'Tempête', 'Poids de la Neige',
       'Glissement et Effondrement de Terrain',
       'Glissement et Eboulement Rocheux', 'Coulée de Boue', 'Divers',
       'Eruption Volcanique', 'Grêle'], dtype=object)

In [6]:
#fréquence de chaque risque
df_cat_nat.value_counts('lib_risque_jo',normalize=True)*100

lib_risque_jo
Inondations et/ou Coulées de Boue              56.263636
Sécheresse                                     18.242401
Mouvement de Terrain                           12.454802
Tempête                                         6.206696
Chocs Mécaniques liés à l'action des Vagues     2.633062
Glissement de Terrain                           1.496555
Poids de la Neige                               1.057519
Inondations Remontée Nappe                      0.578990
Grêle                                           0.571705
Secousse Sismique                               0.302915
Avalanche                                       0.050230
Effondrement et/ou Affaisement                  0.046779
Vents Cycloniques                               0.032976
Eboulement et/ou Chute de Blocs                 0.026841
Divers                                          0.024923
Lave Torrentielle                               0.002684
Coulée de Boue                                  0.002301
Raz de Marée                                    0.002301
Glissement et Effondrement de Terrain           0.001917
Eruption Volcanique                             0.000383
Glissement et Eboulement Rocheux                0.000383
Name: proportion, dtype: float64

In [15]:
df_cat_nat[df_cat_nat["cod_commune"].str.startswith('13055')]

,cod_nat_catnat,cod_commune,lib_commune,num_risque_jo,lib_risque_jo,dat_deb,dat_fin,dat_pub_arrete,dat_pub_jo,dat_maj
2817,INTE0000117A,13055,Marseille,ICB,Inondations et/ou Coulées de Boue,1999-10-20,1999-10-21,2000-03-03,2000-03-19,2022-05-24 11:23:51.534
4641,INTE0000626A,13055,Marseille,ICB,Inondations et/ou Coulées de Boue,2000-09-19,2000-09-19,2000-11-06,2000-11-22,2022-05-24 11:24:15.172
5557,INTE0000771A,13055,Marseille,SEC,Sécheresse,1992-01-01,1993-06-30,2000-12-27,2000-12-29,2022-05-24 11:24:17.246
5558,INTE0000771A,13055,Marseille,SEC,Sécheresse,1992-01-01,1993-06-30,2000-12-27,2000-12-29,2022-05-24 11:24:17.246
5559,INTE0000771A,13055,Marseille,SEC,Sécheresse,1998-01-01,1998-06-30,2000-12-27,2000-12-29,2022-05-24 11:24:18.250
...,...,...,...,...,...,...,...,...,...,...
240230,INTE2501371A,13055,Marseille,ICB,Inondations et/ou Coulées de Boue,2024-10-07 02:00:00,2024-10-07 02:00:00,2025-01-19 01:00:00,2025-02-05 01:00:00,2025-02-11 01:00:00
241258,INTE2526475A,13055,Marseille,ICB,Inondations et/ou Coulées de Boue,2025-09-20 02:00:00,2025-09-21 02:00:00,2025-09-24 02:00:00,2025-09-26 02:00:00,2025-10-02 02:00:00
253601,NOR19821118,13055,Marseille,ICB,Inondations et/ou Coulées de Boue,1982-11-06 01:00:00,1982-11-10 01:00:00,1982-11-18 01:00:00,1982-11-19 01:00:00,2022-05-20 02:00:00
253602,NOR19821118,13055,Marseille,TMP,Tempête,1982-11-06 01:00:00,1982-11-10 01:00:00,1982-11-18 01:00:00,1982-11-19 01:00:00,2022-05-20 02:00:00
260293,IOME2226252A,13055,Marseille,ICB,Inondations et/ou Coulées de Boue,2022-08-17 02:00:00,2022-08-17 02:00:00,2022-09-19 02:00:00,2022-10-12 02:00:00,2022-12-14 01:00:00

In [9]:
query = """
SELECT e.siren,
        e.dept,
        e.total_pop_tot,
    df_cat_nat.nb_cat_nat,
    ROUND(1.0*df_cat_nat.nb_cat_nat / e.superficie_km2, 3) AS cat_nat_per_km2
FROM df_epci AS e
LEFT JOIN df_cat_nat
ON e.siren = df_cat_nat.siren
"""

df_cat_nat_final = duckdb.sql(query)

BinderException: Binder Error: Table "df_cat_nat" does not have a column named "siren"

Candidate bindings: : "lib_risque_jo"

In [52]:
df_cat_nat_final.write_csv("./data/processed/cat_nat_epci.csv")