In [1]:
import os
import requests
import pandas as pd
import duckdb

In [2]:
url = "https://www.data.gouv.fr/api/1/datasets/r/2ce43ade-8d2c-4d1d-81da-ca06c82abc68"
response = requests.get(url)
with open("../data/raw/pharmacies.csv", "wb") as f:
    f.write(response.content)

In [3]:

df_raw = pd.read_csv("../data/raw/pharmacies.csv", sep=";", dtype=str,skiprows=1,header = None)

In [4]:
df_raw

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,structureet,010000024,010780054,CH DE FLEYRIAT,CENTRE HOSPITALIER DE BOURG-EN-BRESSE FLEYRIAT,NaN,NaN,900,RTE,DE PARIS,...,26010004500012,8610Z,03,ARS établissements Publics de santé dotation g...,1,Etablissement public de santé,1979-02-13,1979-02-13,2020-02-04,NaN
1,structureet,010000032,010780062,CH BUGEY SUD,CENTRE HOSPITALIER BUGEY SUD,NaN,NaN,700,AV,DE NARVIK,...,26010003700068,8610Z,03,ARS établissements Publics de santé dotation g...,1,Etablissement public de santé,1901-01-01,1901-01-01,2021-07-07,NaN
2,structureet,010000065,010780096,CH DE TREVOUX - MONTPENSIER,CENTRE HOSPITALIER DE TREVOUX - MONTPENSIER,NaN,NaN,14,R,DE L'HOPITAL,...,26010028400017,8610Z,03,ARS établissements Publics de santé dotation g...,1,Etablissement public de santé,1901-01-01,1901-01-01,2018-01-12,NaN
3,structureet,010000081,010780112,CH DU PAYS DE GEX,CENTRE HOSPITALIER DU PAYS DE GEX,NaN,NaN,160,R,MARC PANISSOD,...,26010010200011,8610Z,03,ARS établissements Publics de santé dotation g...,1,Etablissement public de santé,1901-01-01,1901-01-01,2020-02-04,NaN
4,structureet,010000099,010780120,CH DE MEXIMIEUX,CENTRE HOSPITALIER DE MEXIMIEUX,NaN,NaN,13,AV,DU DOCTEUR BOYER,...,26010013600019,8610Z,03,ARS établissements Publics de santé dotation g...,1,Etablissement public de santé,1945-01-01,1945-01-01,2020-06-30,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102538,structureet,980503320,980503312,OUNONO NA MAECHA,NaN,NaN,NaN,729,R,DE L'AVENIR,...,52858351100027,NaN,08,Président du Conseil Départemental,NaN,NaN,2023-07-25,2023-06-22,2025-09-26,NaN
102539,structureet,980503346,980503338,USAIDIYA,NaN,NaN,NaN,28,R,BABOU SALAMA,...,91320786600017,NaN,08,Président du Conseil Départemental,NaN,NaN,2023-09-04,2022-11-24,2025-09-26,NaN
102540,structureet,980503395,980503387,LA MAISON DU BONHEUR,NaN,NaN,NaN,2,R,BACARI DJOUMOI,...,94210204700019,NaN,08,Président du Conseil Départemental,NaN,NaN,2025-03-20,2025-01-17,2025-10-30,NaN
102541,structureet,980600027,980600019,HOPITAL DE SIA,NaN,NaN,NaN,NaN,NaN,NaN,...,13000323900014,NaN,99,Indéterminé,1,Etablissement public de santé,2024-10-30,2024-10-30,2024-10-30,NaN
102542,structureet,980600035,980600019,HOPITAL DE KALEVELEVE,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,99,Indéterminé,1,Etablissement public de santé,2024-10-30,2024-10-30,2024-10-30,NaN

In [5]:
df = df_raw.iloc[:, [12,13,15, 19]]

In [6]:
df

         12  13                   15                                    19
0       451  01         01440 VIRIAT             Centre Hospitalier (C.H.)
1       034  01         01300 BELLEY             Centre Hospitalier (C.H.)
2       427  01  01606 TREVOUX CEDEX             Centre Hospitalier (C.H.)
3       173  01      01174 GEX CEDEX  Centre hospitalier, ex Hôpital local
4       244  01      01800 MEXIMIEUX  Centre hospitalier, ex Hôpital local
...     ...  ..                  ...                                   ...
102538  602  9F     97650 BANDRABOUA          Service autonomie aide (SAA)
102539  611  9F      97600 MAMOUDZOU          Service autonomie aide (SAA)
102540  602  9F     97650 BANDRABOUA             Lieux de Vie et d'Accueil
102541  613  9J           98600 UVEA             Centre Hospitalier (C.H.)
102542  611  9J         98620 FUTUNA             Centre Hospitalier (C.H.)

[102543 rows x 4 columns]

In [7]:
df.rename(columns={19: "type", 15: "code_postal", 12 : "code_com", 13: "dept"}, inplace=True)

/tmp/ipykernel_6883/683416371.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={19: "type", 15: "code_postal", 12 : "code_com", 13: "dept"}, inplace=True)

In [8]:
df = df.loc[df["type"].str.startswith("Phar")].reset_index(drop=True)

In [9]:
df

      code_com dept                code_postal                  type
0          004   01    01500 AMBERIEU EN BUGEY  Pharmacie d'Officine
1          004   01    01500 AMBERIEU EN BUGEY  Pharmacie d'Officine
2          004   01    01500 AMBERIEU EN BUGEY  Pharmacie d'Officine
3          004   01    01500 AMBERIEU EN BUGEY  Pharmacie d'Officine
4          005   01  01330 AMBERIEUX EN DOMBES  Pharmacie d'Officine
...        ...  ...                        ...                   ...
20136      607   9F              97660 DEMBENI  Pharmacie d'Officine
20137      611   9F            97600 MAMOUDZOU  Pharmacie d'Officine
20138      608   9F             97615 DZAOUDZI  Pharmacie d'Officine
20139      614   9F             97670 OUANGANI  Pharmacie d'Officine
20140      611   9F            97600 MAMOUDZOU  Pharmacie d'Officine

[20141 rows x 4 columns]

In [10]:
df['code_insee']=df['dept'] + df['code_com']

In [11]:
df

,code_com,dept,code_postal,type,code_insee
0,004,01,01500 AMBERIEU EN BUGEY,Pharmacie d'Officine,01004
1,004,01,01500 AMBERIEU EN BUGEY,Pharmacie d'Officine,01004
2,004,01,01500 AMBERIEU EN BUGEY,Pharmacie d'Officine,01004
3,004,01,01500 AMBERIEU EN BUGEY,Pharmacie d'Officine,01004
4,005,01,01330 AMBERIEUX EN DOMBES,Pharmacie d'Officine,01005
...,...,...,...,...,...
20136,607,9F,97660 DEMBENI,Pharmacie d'Officine,9F607
20137,611,9F,97600 MAMOUDZOU,Pharmacie d'Officine,9F611
20138,608,9F,97615 DZAOUDZI,Pharmacie d'Officine,9F608
20139,614,9F,97670 OUANGANI,Pharmacie d'Officine,9F614
20140,611,9F,97600 MAMOUDZOU,Pharmacie d'Officine,9F611

In [12]:
df[df["code_insee"].str.startswith("75")]

      code_com dept  code_postal                  type code_insee
13998      101   75  75001 PARIS  Pharmacie d'Officine      75101
13999      101   75  75001 PARIS  Pharmacie d'Officine      75101
14000      101   75  75001 PARIS  Pharmacie d'Officine      75101
14001      101   75  75001 PARIS  Pharmacie d'Officine      75101
14002      101   75  75001 PARIS  Pharmacie d'Officine      75101
...        ...  ...          ...                   ...        ...
14851      103   75  75003 PARIS  Pharmacie d'Officine      75103
14852      111   75  75011 PARIS  Pharmacie d'Officine      75111
14853      112   75  75012 PARIS  Pharmacie d'Officine      75112
14854      116   75  75116 PARIS  Pharmacie d'Officine      75116
14855      102   75  75002 PARIS  Pharmacie d'Officine      75102

[858 rows x 5 columns]

In [16]:
ci_marseille = [13200 + i for i in range(1,17)]
ci_marseille = [str(i) for i in ci_marseille]
ci_marseille

['13201',
 '13202',
 '13203',
 '13204',
 '13205',
 '13206',
 '13207',
 '13208',
 '13209',
 '13210',
 '13211',
 '13212',
 '13213',
 '13214',
 '13215',
 '13216']

In [29]:
df.loc[df['code_insee'].isin(ci_marseille),'code_insee'] = '13055'

In [22]:
ci_lyon = [69380 + i for i in range(1,10)]
ci_lyon = [str(i) for i in ci_lyon]
ci_lyon

['69381',
 '69382',
 '69383',
 '69384',
 '69385',
 '69386',
 '69387',
 '69388',
 '69389']

In [27]:
df.loc[df["code_insee"].isin(ci_lyon),"code_insee"] = '69123'

In [28]:
df[df["code_postal"].str.contains("LYON")]

      code_com dept               code_postal                  type code_insee
3977       377   27      27480 LYONS LA FORET  Pharmacie d'Officine      27377
7361       059   42  42140 CHAZELLES SUR LYON  Pharmacie d'Officine      42059
7362       059   42  42140 CHAZELLES SUR LYON  Pharmacie d'Officine      42059
7363       059   42  42140 CHAZELLES SUR LYON  Pharmacie d'Officine      42059
12874      202   69    69110 STE FOY LES LYON  Pharmacie d'Officine      69202
...        ...  ...                       ...                   ...        ...
13224      389   69                69009 LYON  Pharmacie d'Officine      69123
13225      389   69                69009 LYON  Pharmacie d'Officine      69123
13226      389   69                69009 LYON  Pharmacie d'Officine      69123
13227      389   69                69009 LYON  Pharmacie d'Officine      69123
13228      389   69                69009 LYON  Pharmacie d'Officine      69123

[165 rows x 5 columns]

In [31]:
df.loc[df["code_insee"].str.startswith("75"), "code_insee"] = "75056"

In [33]:
df_epci = pd.read_csv("../data/processed/epci_membres.csv", sep=",", dtype=str)
df_epci

,code_insee,nom,pop_tot_commune,pop_mun_commune,siren,epci_nom,epci_type,epci_modeFinancement,total_pop_tot,total_pop_mun,superficie_hectare,superficie_km2,dept_com,bassin_vie,dept_epci
0,01304,Pont-d'Ain,2912,2862,200029999,CC Rives de l'Ain - Pays du Cerdon,CC,FPU,15156,14873,1122.0,11.0,01,01304,01
1,01199,Jujurieux,2246,2209,200029999,CC Rives de l'Ain - Pays du Cerdon,CC,FPU,15156,14873,1548.0,15.0,01,01004,01
2,01363,Saint-Jean-le-Vieux,1873,1799,200029999,CC Rives de l'Ain - Pays du Cerdon,CC,FPU,15156,14873,1517.0,15.0,01,01004,01
3,01314,Priay,1826,1803,200029999,CC Rives de l'Ain - Pays du Cerdon,CC,FPU,15156,14873,1571.0,16.0,01,01004,01
4,01273,Neuville-sur-Ain,1823,1798,200029999,CC Rives de l'Ain - Pays du Cerdon,CC,FPU,15156,14873,1991.0,20.0,01,01004,01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34996,97601,Acoua,5384,5192,200060465,CA du Grand Nord de Mayotte,CA,FPU,60372,59042,1290.0,13.0,97,97611,976
34997,97603,Bandrele,10529,10282,200060473,CC du Sud,CC,FPU,31945,30898,3514.0,35.0,97,97611,976
34998,97606,Chirongui,9197,8920,200060473,CC du Sud,CC,FPU,31945,30898,2590.0,26.0,97,97611,976
34999,97604,Bouéni,6503,6189,200060473,CC du Sud,CC,FPU,31945,30898,1381.0,14.0,97,97611,976
35000,97609,Kani-Kéli,5716,5507,200060473,CC du Sud,CC,FPU,31945,30898,2004.0,20.0,97,97611,976

In [126]:
df_epci

,code_insee,nom,pop_tot_commune,pop_mun_commune,siren,epci_nom,epci_type,epci_modeFinancement,total_pop_tot,total_pop_mun,superficie_hectare,superficie_km2,dept_com,bassin_vie,dept_epci
0,01304,Pont-d'Ain,2912,2862,200029999,CC Rives de l'Ain - Pays du Cerdon,CC,FPU,15156,14873,1122.0,11.0,01,01304,01
1,01199,Jujurieux,2246,2209,200029999,CC Rives de l'Ain - Pays du Cerdon,CC,FPU,15156,14873,1548.0,15.0,01,01004,01
2,01363,Saint-Jean-le-Vieux,1873,1799,200029999,CC Rives de l'Ain - Pays du Cerdon,CC,FPU,15156,14873,1517.0,15.0,01,01004,01
3,01314,Priay,1826,1803,200029999,CC Rives de l'Ain - Pays du Cerdon,CC,FPU,15156,14873,1571.0,16.0,01,01004,01
4,01273,Neuville-sur-Ain,1823,1798,200029999,CC Rives de l'Ain - Pays du Cerdon,CC,FPU,15156,14873,1991.0,20.0,01,01004,01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34996,97601,Acoua,5384,5192,200060465,CA du Grand Nord de Mayotte,CA,FPU,60372,59042,1290.0,13.0,97,97611,976
34997,97603,Bandrele,10529,10282,200060473,CC du Sud,CC,FPU,31945,30898,3514.0,35.0,97,97611,976
34998,97606,Chirongui,9197,8920,200060473,CC du Sud,CC,FPU,31945,30898,2590.0,26.0,97,97611,976
34999,97604,Bouéni,6503,6189,200060473,CC du Sud,CC,FPU,31945,30898,1381.0,14.0,97,97611,976
35000,97609,Kani-Kéli,5716,5507,200060473,CC du Sud,CC,FPU,31945,30898,2004.0,20.0,97,97611,976

In [37]:
 query = """
    SELECT
        df_epci.dept_epci AS dept_id,
        df_epci.siren AS id_epci,
        df_epci.epci_nom AS epci_lib,
        'i066' AS id_indicator,
        round(COUNT(df.code_insee) / cast(df_epci.total_pop_mun AS FLOAT) * 10000,2) AS valeur_brute,
        '2026' AS annee
    FROM df_epci
    LEFT JOIN df
        ON df.code_insee = df_epci.code_insee
    GROUP BY df_epci.siren, df_epci.dept_epci, df_epci.epci_nom, df_epci.total_pop_mun
    ORDER BY df_epci.dept_epci, df_epci.siren
        """

nb_pharma_epci = duckdb.sql(query)
nb_pharma_epci

┌─────────┬───────────┬────────────────────────────────────────────────────────────┬──────────────┬──────────────┬─────────┐
│ dept_id │  id_epci  │                          epci_lib                          │ id_indicator │ valeur_brute │  annee  │
│ varchar │  varchar  │                          varchar                           │   varchar    │    float     │ varchar │
├─────────┼───────────┼────────────────────────────────────────────────────────────┼──────────────┼──────────────┼─────────┤
│ 01      │ 200029999 │ CC Rives de l'Ain - Pays du Cerdon                         │ i066         │         2.69 │ 2026    │
│ 01      │ 200040350 │ CC Bugey Sud                                               │ i066         │         2.35 │ 2026    │
│ 01      │ 200042497 │ CC Dombes Saône Vallée                                     │ i066         │         1.96 │ 2026    │
│ 01      │ 200042935 │ CA Haut-Bugey Agglomération                                │ i066         │         2.98 │ 2026    │
│ 01      │ 200069193 │ CC de la Dombes                                            │ i066         │         2.22 │ 2026    │
│ 01      │ 200070118 │ CC Val de Saône Centre                                     │ i066         │         1.43 │ 2026    │
│ 01      │ 200070555 │ CC de la Veyle                                             │ i066         │         1.72 │ 2026    │
│ 01      │ 200071371 │ CC Bresse et Saône                                         │ i066         │         2.33 │ 2026    │
│ 01      │ 200071751 │ CA du Bassin de Bourg-en-Bresse                            │ i066         │          2.5 │ 2026    │
│ 01      │ 240100610 │ CC de la Côtière à Montluel                                │ i066         │         1.96 │ 2026    │
│ ·       │     ·     │              ·                                             │  ·           │           ·  │  ·      │
│ ·       │     ·     │              ·                                             │  ·           │           ·  │  ·      │
│ ·       │     ·     │              ·                                             │  ·           │           ·  │  ·      │
│ 974     │ 249740077 │ CA CIVIS (Communauté Intercommunale des Villes Solidaires) │ i066         │          0.0 │ 2026    │
│ 974     │ 249740085 │ CA du Sud                                                  │ i066         │          0.0 │ 2026    │
│ 974     │ 249740093 │ CA Intercommunale de la Réunion Est (CIREST)               │ i066         │          0.0 │ 2026    │
│ 974     │ 249740101 │ CA Territoire de la Côte Ouest (TCO)                       │ i066         │          0.0 │ 2026    │
│ 974     │ 249740119 │ CA Intercommunale du Nord de la Réunion (CINOR)            │ i066         │          0.0 │ 2026    │
│ 976     │ 200050532 │ CC de Petite-Terre                                         │ i066         │          0.0 │ 2026    │
│ 976     │ 200059871 │ CC du Centre-Ouest                                         │ i066         │          0.0 │ 2026    │
│ 976     │ 200060457 │ CA de Dembeni / Mamoudzou                                  │ i066         │          0.0 │ 2026    │
│ 976     │ 200060465 │ CA du Grand Nord de Mayotte                                │ i066         │          0.0 │ 2026    │
│ 976     │ 200060473 │ CC du Sud                                                  │ i066         │          0.0 │ 2026    │
├─────────┴───────────┴────────────────────────────────────────────────────────────┴──────────────┴──────────────┴─────────┤
│ 1267 rows (20 shown)                                                                                           6 columns │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [91]:
nb_pharma_rives_ain

np.int64(18)

In [71]:
df_epci[df_epci['siren'] == '200000172']

,code_insee,nom,pop_tot_commune,pop_mun_commune,siren,epci_nom,epci_type,epci_modeFinancement,total_pop_tot,total_pop_mun,superficie_hectare,superficie_km2,dept_com,bassin_vie,dept_epci
28881,74042,Bonneville,13736,13320,200000172,CC Faucigny - Glières,CC,FPU,29204,28363,2724.0,27.0,74,74042,74
28882,74164,Marignier,6612,6432,200000172,CC Faucigny - Glières,CC,FPU,29204,28363,2062.0,21.0,74,74081,74
28883,74087,Contamine-sur-Arve,2498,2374,200000172,CC Faucigny - Glières,CC,FPU,29204,28363,671.0,7.0,74,74012,74
28884,74024,Ayse,2372,2325,200000172,CC Faucigny - Glières,CC,FPU,29204,28363,1041.0,10.0,74,74042,74
28885,74212,Glières-Val-de-Borne,1863,1825,200000172,CC Faucigny - Glières,CC,FPU,29204,28363,5349.0,53.0,74,74042,74
28886,74312,Vougy,1650,1622,200000172,CC Faucigny - Glières,CC,FPU,29204,28363,405.0,4.0,74,74042,74
28887,74049,Brizon,473,465,200000172,CC Faucigny - Glières,CC,FPU,29204,28363,1031.0,10.0,74,74042,74

In [64]:
df_densite_parma_i066 = df_densite_parma_i066.df()