In [2]:
import duckdb
import pandas as pd
import os

In [3]:
df_dist_urg = pd.read_csv("../data/data_dist_soin/raw/dist_urgence.csv",skiprows=2,sep=';')
df_dist_urg

,Code,Libellé,Distance à la structure la plus proche 2024
0,01001,L'Abergement-Clémenciat,26
1,01002,L'Abergement-de-Varey,15
2,01004,Ambérieu-en-Bugey,0
3,01005,Ambérieux-en-Dombes,18
4,01006,Ambléon,11
...,...,...,...
34914,97615,Pamandzi,7
34915,97616,Sada,23
34916,97617,Tsingoni,19
34917,97701,Saint-Barthélemy,N/A - résultat non disponible
34918,97801,Saint-Martin,N/A - résultat non disponible

In [6]:
df_dist_urg[df_dist_urg['Code'].str.startswith("132")]

,Code,Libellé,Distance à la structure la plus proche 2024
4402,13201,Marseille 1er Arrondissement,2
4403,13202,Marseille 2e Arrondissement,0
4404,13203,Marseille 3e Arrondissement,0
4405,13204,Marseille 4e Arrondissement,0
4406,13205,Marseille 5e Arrondissement,0
4407,13206,Marseille 6e Arrondissement,0
4408,13207,Marseille 7e Arrondissement,2
4409,13208,Marseille 8e Arrondissement,0
4410,13209,Marseille 9e Arrondissement,6
4411,13210,Marseille 10e Arrondissement,6
4412,13211,Marseille 11e Arrondissement,0
4413,13212,Marseille 12e Arrondissement,0
4414,13213,Marseille 13e Arrondissement,0
4415,13214,Marseille 14e Arrondissement,0
4416,13215,Marseille 15e Arrondissement,0
4417,13216,Marseille 16e Arrondissement,0

In [7]:
df_dist_urg[df_dist_urg['Code'].str.startswith("693")]

,Code,Libellé,Distance à la structure la plus proche 2024
27205,69381,Lyon 1er Arrondissement,2
27206,69382,Lyon 2e Arrondissement,2
27207,69383,Lyon 3e Arrondissement,0
27208,69384,Lyon 4e Arrondissement,0
27209,69385,Lyon 5e Arrondissement,4
27210,69386,Lyon 6e Arrondissement,1
27211,69387,Lyon 7e Arrondissement,0
27212,69388,Lyon 8e Arrondissement,0
27213,69389,Lyon 9e Arrondissement,0

In [3]:
df_dist_urg[df_dist_urg['Code'].str.startswith("75")]

,Code,Libellé,Distance à la structure la plus proche 2024
29217,75101,Paris 1er Arrondissement,0
29218,75102,Paris 2e Arrondissement,0
29219,75103,Paris 3e Arrondissement,0
29220,75104,Paris 4e Arrondissement,0
29221,75105,Paris 5e Arrondissement,2
29222,75106,Paris 6e Arrondissement,3
29223,75107,Paris 7e Arrondissement,3
29224,75108,Paris 8e Arrondissement,4
29225,75109,Paris 9e Arrondissement,2
29226,75110,Paris 10e Arrondissement,0
29227,75111,Paris 11e Arrondissement,2
29228,75112,Paris 12e Arrondissement,0
29229,75113,Paris 13e Arrondissement,0
29230,75114,Paris 14e Arrondissement,0
29231,75115,Paris 15e Arrondissement,0
29232,75116,Paris 16e Arrondissement,4
29233,75117,Paris 17e Arrondissement,3
29234,75118,Paris 18e Arrondissement,0
29235,75119,Paris 19e Arrondissement,0
29236,75120,Paris 20e Arrondissement,0

In [4]:
df_dist_urg['Code'] = df_dist_urg['Code'].apply(lambda x: '75000' if x.startswith('75') else x)

In [6]:
df_dist_urg[df_dist_urg['Code'].str.startswith("75")]

,Code,Libellé,Distance à la structure la plus proche 2024
29217,75000,Paris 1er Arrondissement,0
29218,75000,Paris 2e Arrondissement,0
29219,75000,Paris 3e Arrondissement,0
29220,75000,Paris 4e Arrondissement,0
29221,75000,Paris 5e Arrondissement,2
29222,75000,Paris 6e Arrondissement,3
29223,75000,Paris 7e Arrondissement,3
29224,75000,Paris 8e Arrondissement,4
29225,75000,Paris 9e Arrondissement,2
29226,75000,Paris 10e Arrondissement,0
29227,75000,Paris 11e Arrondissement,2
29228,75000,Paris 12e Arrondissement,0
29229,75000,Paris 13e Arrondissement,0
29230,75000,Paris 14e Arrondissement,0
29231,75000,Paris 15e Arrondissement,0
29232,75000,Paris 16e Arrondissement,4
29233,75000,Paris 17e Arrondissement,3
29234,75000,Paris 18e Arrondissement,0
29235,75000,Paris 19e Arrondissement,0
29236,75000,Paris 20e Arrondissement,0

In [9]:
mapping = {
    "Code": "code_insee",
    "Libellé": "nom_commune",
    "Distance à la structure la plus proche 2024": "dist_urgence_min"
}
 # conversion DuckDB → pandas
df_dist_urg = df_dist_urg.rename(columns=mapping)

In [10]:
df_dist_urg.drop(columns=['nom_commune'],inplace=True)

In [17]:
#on supprime les lignes où dist_urg_min est "'N/A - résultat non disponible'"
df_dist_urg = df_dist_urg[~df_dist_urg['dist_urgence_min'].str.contains("N/A")]

In [19]:
df_dist_urg['dist_urgence_min'] = df_dist_urg['dist_urgence_min'].str.replace(',','.').astype(float)

AttributeError: Can only use .str accessor with string values!

In [20]:
#on groupe par code_insee en fisant la moyenne ds distance
df_dist_urg = df_dist_urg.groupby('code_insee',as_index=False).agg({'dist_urgence_min':'mean'})

In [22]:
df_dist_urg[df_dist_urg['code_insee'].str.startswith("75")]

      code_insee  dist_urgence_min
29208      75000              1.15

In [6]:
#on retraduis en objet duckdb
df_dist_urg = duckdb.from_df(df_dist_urg)

In [47]:
df_com = duckdb.read_csv("./data/processed/communes_france_2025.csv",sep=",")
df_com

┌────────────┬─────────────────────────┬─────────────────────────┬──────────┬──────────────────────┬──────────┬──────────────┬───────────┬───────────────────────────────────────────┬────────────┬────────────────┬─────────────────┐
│ code_insee │      nom_standard       │     nom_sans_accent     │ reg_code │       reg_nom        │ dep_code │   dep_nom    │ epci_code │                 epci_nom                  │ population │ superficie_km2 │ densite_hab_km2 │
│  varchar   │         varchar         │         varchar         │  int64   │       varchar        │ varchar  │   varchar    │  varchar  │                  varchar                  │   int64    │     int64      │     double      │
├────────────┼─────────────────────────┼─────────────────────────┼──────────┼──────────────────────┼──────────┼──────────────┼───────────┼───────────────────────────────────────────┼────────────┼────────────────┼─────────────────┤
│ 01001      │ L'Abergement-Clémenciat │ l-abergement-clemenciat │       84 │ Auvergne-Rhône-Alpes │ 01       │ Ain          │ 200069193 │ CC de la Dombes                           │        832 │             16 │            53.0 │
│ 01002      │ L'Abergement-de-Varey   │ l-abergement-de-varey   │       84 │ Auvergne-Rhône-Alpes │ 01       │ Ain          │ 240100883 │ CC de la Plaine de l'Ain                  │        267 │              9 │            29.0 │
│ 01004      │ Ambérieu-en-Bugey       │ amberieu-en-bugey       │       84 │ Auvergne-Rhône-Alpes │ 01       │ Ain          │ 240100883 │ CC de la Plaine de l'Ain                  │      14854 │             24 │           607.0 │
│ 01005      │ Ambérieux-en-Dombes     │ amberieux-en-dombes     │       84 │ Auvergne-Rhône-Alpes │ 01       │ Ain          │ 200042497 │ CC Dombes Saône Vallée                    │       1897 │             16 │           118.0 │
│ 01006      │ Ambléon                 │ ambleon                 │       84 │ Auvergne-Rhône-Alpes │ 01       │ Ain          │ 200040350 │ CC Bugey Sud                              │        113 │              6 │            19.0 │
│ 01007      │ Ambronay                │ ambronay                │       84 │ Auvergne-Rhône-Alpes │ 01       │ Ain          │ 240100883 │ CC de la Plaine de l'Ain                  │       2833 │             34 │            84.0 │
│ 01008      │ Ambutrix                │ ambutrix                │       84 │ Auvergne-Rhône-Alpes │ 01       │ Ain          │ 240100883 │ CC de la Plaine de l'Ain                  │        768 │              5 │           148.0 │
│ 01009      │ Andert-et-Condon        │ andert-et-condon        │       84 │ Auvergne-Rhône-Alpes │ 01       │ Ain          │ 200040350 │ CC Bugey Sud                              │        322 │              7 │            46.0 │
│ 01010      │ Anglefort               │ anglefort               │       84 │ Auvergne-Rhône-Alpes │ 01       │ Ain          │ 200070852 │ CC Usses et Rhône                         │       1125 │             29 │            38.0 │
│ 01011      │ Apremont                │ apremont                │       84 │ Auvergne-Rhône-Alpes │ 01       │ Ain          │ 200042935 │ CA Haut - Bugey Agglomération             │        383 │             15 │            25.0 │
│   ·        │    ·                    │    ·                    │        · │          ·           │ ·        │  ·           │     ·     │               ·                           │         ·  │              · │              ·  │
│   ·        │    ·                    │    ·                    │        · │          ·           │ ·        │  ·           │     ·     │               ·                           │         ·  │              · │              ·  │
│   ·        │    ·                    │    ·                    │        · │          ·           │ ·        │  ·           │     ·     │               ·                           │         ·  │              · │              ·  │
│ 28113      │ Coulombs                │ coulombs                │       24 │ Centre-Val de Loire  │ 28       │ Eure-et-Loir │ 200069953 │ CC des Portes Euréliennes d'Île-de-France │       1331 │             13 │           105.0 │
│ 28114      │ Courbehaye              │ courbehaye              │       24 │ Centre-Val de Loire  │ 28       │ Eure-et-Loir │ 200070159 │ CC Cœur de Beauce                         │        136 │             20 │             7.0 │
│ 28116      │ Courville-sur-Eure      │ courville-sur-eure      │       24 │ Centre-Val de Loire  │ 28       │ Eure-et-Loir │ 200058360 │ CC entre Beauce et Perche                 │       2806 │             11 │           251.0 │
│ 28117      │ Crécy-Couvé             │ crecy-couve             │       24 │ Centre-Val de Loire  │ 28       │ Eure-et-Loir │ 200040277 │ CA Agglo du Pays de Dreux                 │        270 │              7 │            40.0 │
│ 28118      │ Croisilles              │ croisilles              │       24 │ Centre-Val de Loire  │ 28       │ Eure-et-Loir │ 200069953 │ CC des Portes Euréliennes d'Île-de-France │        424 │              6 │            73.0 │
│ 28119      │ La Croix-du-Perche      │ la-croix-du-perche      │       24 │ Centre-Val de Loire  │ 28       │ Eure-et-Loir │ 200070167 │ CC Terres de Perche                       │        148 │             13 │            12.0 │
│ 28120      │ Crucey-Villages         │ crucey-villages         │       24 │ Centre-Val de Loire  │ 28       │ Eure-et-Loir │ 200040277 │ CA Agglo du Pays de Dreux                 │        445 │             44 │            10.0 │
│ 28121      │ Dambron                 │ dambron                 │       24 │ Centre-Val de Loire  │ 28       │ Eure-et-Loir │ 200070159 │ CC Cœur de Beauce                         │        105 │             12 │             9.0 │
│ 28122      │ Dammarie                │ dammarie                │       24 │ Centre-Val de Loire  │ 28       │ Eure-et-Loir │ 200033181 │ CA Chartres Métropole                     │       1495 │             33 │            46.0 │
│ 28123      │ Dampierre-sous-Brou     │ dampierre-sous-brou     │       24 │ Centre-Val de Loire  │ 28       │ Eure-et-Loir │ 200069961 │ CC du Grand Châteaudun                    │        447 │             15 │            31.0 │
├────────────┴─────────────────────────┴─────────────────────────┴──────────┴──────────────────────┴──────────┴──────────────┴───────────┴───────────────────────────────────────────┴────────────┴────────────────┴─────────────────┤
│ ? rows (>9999 rows, 20 shown)                                                                                                                                                                                           12 columns │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [48]:
query = """
SELECT 
    DISTINCT epci_code,
    ROUND(AVG(TRY_CAST(dist_urgence_min AS DOUBLE)),2) AS dist_urgence_moyenne
FROM df_com
LEFT JOIN df_dist_urg
ON df_com.code_insee = df_dist_urg.code_insee
GROUP BY epci_code
"""

df_dist_soin = duckdb.sql(query)

In [24]:
df_dist_pharma = pd.read_csv("../data/data_dist_soin/raw/dist_pharma.csv",skiprows=2,sep=';')
df_dist_pharma

,Code,Libellé,Distance à la pharmacie la plus proche 2024
0,01001,L'Abergement-Clémenciat,5
1,01002,L'Abergement-de-Varey,15
2,01004,Ambérieu-en-Bugey,0
3,01005,Ambérieux-en-Dombes,11
4,01006,Ambléon,11
...,...,...,...
34914,97615,Pamandzi,7
34915,97616,Sada,23
34916,97617,Tsingoni,19
34917,97701,Saint-Barthélemy,N/A - résultat non disponible
34918,97801,Saint-Martin,N/A - résultat non disponible

In [25]:
mapping = {
    "Code": "code_insee",
    "Libellé": "nom_commune",
    "Distance à la pharmacie la plus proche 2024": "dist_pharma_min"
}

df_dist_pharma = df_dist_pharma.rename(columns=mapping)

In [ ]:
df_dist_pharma[df_dist_pharma['code_insee'].str.startswith("75")]
df_dist_pharma['code_insee'] = df_dist_pharma['code_insee'].apply(lambda x: '75056' if x.startswith('75') else x)

      code_insee               nom_commune dist_pharma_min
29217      75101  Paris 1er Arrondissement               0
29218      75102   Paris 2e Arrondissement               0
29219      75103   Paris 3e Arrondissement               0
29220      75104   Paris 4e Arrondissement               0
29221      75105   Paris 5e Arrondissement               0
29222      75106   Paris 6e Arrondissement               0
29223      75107   Paris 7e Arrondissement               0
29224      75108   Paris 8e Arrondissement               0
29225      75109   Paris 9e Arrondissement               0
29226      75110  Paris 10e Arrondissement               0
29227      75111  Paris 11e Arrondissement               0
29228      75112  Paris 12e Arrondissement               0
29229      75113  Paris 13e Arrondissement               0
29230      75114  Paris 14e Arrondissement               0
29231      75115  Paris 15e Arrondissement               0
29232      75116  Paris 16e Arrondissement               0
29233      75117  Paris 17e Arrondissement               0
29234      75118  Paris 18e Arrondissement               0
29235      75119  Paris 19e Arrondissement               0
29236      75120  Paris 20e Arrondissement               0

In [27]:
df_dist_pharma[df_dist_pharma['code_insee'].str.startswith("97")]

      code_insee       nom_commune                dist_pharma_min
34788      97101        Les Abymes                              0
34789      97102     Anse-Bertrand                             14
34790      97103      Baie-Mahault                              0
34791      97104           Baillif                              4
34792      97105       Basse-Terre                              0
...          ...               ...                            ...
34914      97615          Pamandzi                              7
34915      97616              Sada                             23
34916      97617          Tsingoni                             19
34917      97701  Saint-Barthélemy  N/A - résultat non disponible
34918      97801      Saint-Martin  N/A - résultat non disponible

[131 rows x 3 columns]

In [51]:
query ="""
SELECT
    DISTINCT epci_code,
    ROUND(AVG(TRY_CAST(dist_pharma_min AS DOUBLE)),2) AS dist_pharma_moyenne
FROM df_com
LEFT JOIN df_dist_pharma
ON df_com.code_insee = df_dist_pharma.code_insee
GROUP BY epci_code
"""

df_dist_pharma_moy = duckdb.sql(query)

In [52]:
query = """ 
SELECT
    d.epci_code as siren,
    d.dist_urgence_moyenne,
    p.dist_pharma_moyenne
FROM df_dist_soin d
LEFT JOIN df_dist_pharma_moy p
ON d.epci_code = p.epci_code
"""

df_dist_soin_final = duckdb.sql(query)
df_dist_soin_final

┌───────────┬──────────────────────┬─────────────────────┐
│   siren   │ dist_urgence_moyenne │ dist_pharma_moyenne │
│  varchar  │        double        │       double        │
├───────────┼──────────────────────┼─────────────────────┤
│ 200071751 │                17.01 │               12.64 │
│ 240200501 │                19.34 │               12.16 │
│ 200068765 │                28.82 │               18.85 │
│ 200041465 │                46.24 │               16.34 │
│ 200040491 │                12.71 │                7.47 │
│ 240700815 │                18.38 │                9.77 │
│ 241000405 │                43.56 │                8.96 │
│ 200071777 │                35.67 │               29.31 │
│ 241200542 │                37.09 │               33.27 │
│ 200065589 │                19.83 │                7.83 │
│     ·     │                   ·  │                  ·  │
│     ·     │                   ·  │                  ·  │
│     ·     │                   ·  │                  ·  │
│ 200060457 │                  6.0 │                 6.0 │
│ 247000367 │                19.52 │               19.52 │
│ 249730052 │                116.0 │               105.0 │
│ 200072049 │                20.28 │               16.52 │
│ 244400438 │                22.56 │                6.44 │
│ 245900428 │                 8.65 │                2.88 │
│ 200066322 │                14.27 │                8.68 │
│ 245701362 │                 9.77 │                5.85 │
│ 200034601 │                36.47 │                29.0 │
│ 248400285 │                 11.5 │                7.13 │
├───────────┴──────────────────────┴─────────────────────┤
│ 1257 rows (20 shown)                         3 columns │
└────────────────────────────────────────────────────────┘

In [53]:
df_dist_soin_final.write_csv("./data/processed/distance_lieu_soin_epci.csv")