In [2]:
import pandas as pd
import requests
import json
import duckdb
import os

In [3]:
url_json = "https://www.data.gouv.fr/api/1/datasets/r/4f02ce39-2a91-4a8b-85cb-c6a0f912516b"
response = requests.get(url_json)
data = response.json()

In [4]:
df = pd.json_normalize(
    data,
    record_path="membres",
    meta=[
        "code",
        "nom",
        "type",
        "modeFinancement",
        "populationTotale",
        "populationMunicipale"
    ],
    record_prefix="",
    meta_prefix="epci_"
)

In [5]:
df

,code,siren,nom,populationTotale,populationMunicipale,epci_code,epci_nom,epci_type,epci_modeFinancement,epci_populationTotale,epci_populationMunicipale
0,74042,217400423,Bonneville,13736,13320,200000172,CC Faucigny - Glières,CC,FPU,29204,28363
1,74164,217401645,Marignier,6612,6432,200000172,CC Faucigny - Glières,CC,FPU,29204,28363
2,74087,217400878,Contamine-sur-Arve,2498,2374,200000172,CC Faucigny - Glières,CC,FPU,29204,28363
3,74024,217400241,Ayse,2372,2325,200000172,CC Faucigny - Glières,CC,FPU,29204,28363
4,74212,200081446,Glières-Val-de-Borne,1863,1825,200000172,CC Faucigny - Glières,CC,FPU,29204,28363
...,...,...,...,...,...,...,...,...,...,...,...
34866,97407,219740073,Le Port,33940,33670,249740101,CA Territoire de la Côte Ouest (TCO),CA,FPU,221532,218990
34867,97423,219740230,Les Trois-Bassins,7207,7113,249740101,CA Territoire de la Côte Ouest (TCO),CA,FPU,221532,218990
34868,97411,219740115,Saint-Denis,157674,156149,249740119,CA Intercommunale du Nord de la Réunion (CINOR),CA,FPU,218801,216588
34869,97418,219740180,Sainte-Marie,36014,35584,249740119,CA Intercommunale du Nord de la Réunion (CINOR),CA,FPU,218801,216588
34870,97420,219740206,Sainte-Suzanne,25113,24855,249740119,CA Intercommunale du Nord de la Réunion (CINOR),CA,FPU,218801,216588

In [6]:
url_ept = "https://www.data.gouv.fr/api/1/datasets/r/02f8aaad-f23f-4b70-9aa7-fee55c2c01d1"
response_ept= requests.get(url_ept)
data_ept = response_ept.json()

In [7]:
data_ept

[{'code': '200057867',
  'nom': 'Plaine Commune',
  'type': 'EPT',
  'modeFinancement': '',
  'membres': [{'code': '93001',
    'siren': '219300019',
    'nom': 'Aubervilliers',
    'populationTotale': 88529,
    'populationMunicipale': 88365},
   {'code': '93027',
    'siren': '219300274',
    'nom': 'La Courneuve',
    'populationTotale': 47285,
    'populationMunicipale': 47167},
   {'code': '93031',
    'siren': '219300316',
    'nom': 'Épinay-sur-Seine',
    'populationTotale': 52944,
    'populationMunicipale': 52833},
   {'code': '93039',
    'siren': '219300399',
    'nom': "L'Île-Saint-Denis",
    'populationTotale': 8715,
    'populationMunicipale': 8696},
   {'code': '93066',
    'nom': 'Saint-Denis',
    'populationTotale': 149936,
    'populationMunicipale': 149077},
   {'code': '93070',
    'siren': '219300704',
    'nom': 'Saint-Ouen-sur-Seine',
    'populationTotale': 53747,
    'populationMunicipale': 53615},
   {'code': '93072',
    'siren': '219300720',
    'nom': 'Stains',
    'populationTotale': 41471,
    'populationMunicipale': 41388},
   {'code': '93079',
    'siren': '219300795',
    'nom': 'Villetaneuse',
    'populationTotale': 12599,
    'populationMunicipale': 12530}],
  'populationTotale': 455226,
  'populationMunicipale': 453671},
 {'code': '200057875',
  'nom': 'Est Ensemble',
  'type': 'EPT',
  'modeFinancement': '',
  'membres': [{'code': '93006',
    'siren': '219300068',
    'nom': 'Bagnolet',
    'populationTotale': 43234,
    'populationMunicipale': 43086},
   {'code': '93008',
    'siren': '219300084',
    'nom': 'Bobigny',
    'populationTotale': 57035,
    'populationMunicipale': 56927},
   {'code': '93010',
    'siren': '219300100',
    'nom': 'Bondy',
    'populationTotale': 50762,
    'populationMunicipale': 50595},
   {'code': '93045',
    'siren': '219300456',
    'nom': 'Les Lilas',
    'populationTotale': 23968,
    'populationMunicipale': 23843},
   {'code': '93048',
    'siren': '219300480',
    'nom': 'Montreuil',
    'populationTotale': 112549,
    'populationMunicipale': 111934},
   {'code': '93053',
    'siren': '219300530',
    'nom': 'Noisy-le-Sec',
    'populationTotale': 45634,
    'populationMunicipale': 45510},
   {'code': '93055',
    'siren': '219300555',
    'nom': 'Pantin',
    'populationTotale': 62083,
    'populationMunicipale': 61929},
   {'code': '93061',
    'siren': '219300613',
    'nom': 'Le Pré-Saint-Gervais',
    'populationTotale': 17049,
    'populationMunicipale': 16993},
   {'code': '93063',
    'siren': '219300639',
    'nom': 'Romainville',
    'populationTotale': 37224,
    'populationMunicipale': 37152}],
  'populationTotale': 449538,
  'populationMunicipale': 447969},
 {'code': '200057941',
  'nom': 'Paris Est Marne et Bois',
  'type': 'EPT',
  'modeFinancement': '',
  'membres': [{'code': '94015',
    'siren': '219400157',
    'nom': 'Bry-sur-Marne',
    'populationTotale': 18807,
    'populationMunicipale': 18503},
   {'code': '94017',
    'siren': '219400173',
    'nom': 'Champigny-sur-Marne',
    'populationTotale': 78400,
    'populationMunicipale': 78072},
   {'code': '94018',
    'siren': '219400181',
    'nom': 'Charenton-le-Pont',
    'populationTotale': 29019,
    'populationMunicipale': 28830},
   {'code': '94033',
    'siren': '219400330',
    'nom': 'Fontenay-sous-Bois',
    'populationTotale': 54209,
    'populationMunicipale': 53757},
   {'code': '94042',
    'siren': '219400421',
    'nom': 'Joinville-le-Pont',
    'populationTotale': 20675,
    'populationMunicipale': 20525},
   {'code': '94046',
    'siren': '219400462',
    'nom': 'Maisons-Alfort',
    'populationTotale': 57144,
    'populationMunicipale': 56799},
   {'code': '94052',
    'siren': '219400520',
    'nom': 'Nogent-sur-Marne',
    'populationTotale': 32701,
    'populationMunicipale': 32455},
   {'code': '94058',
    'siren': '219400587',
    'nom': 'Le Perreux-sur-Marne',
    'populationTotale': 35566,
    'populationMunicipale': 35260},
   {'code': '94067',
    'siren': '219400678',
    'nom': 'Saint-Mandé',
    'populationTotale': 21228,
    'populationMunicipale': 21071},
   {'code': '94068',
    'siren': '219400686',
    'nom': 'Saint-Maur-des-Fossés',
    'populationTotale': 77413,
    'populationMunicipale': 76572},
   {'code': '94069',
    'siren': '219400694',
    'nom': 'Saint-Maurice',
    'populationTotale': 14554,
    'populationMunicipale': 14506},
   {'code': '94079',
    'siren': '219400793',
    'nom': 'Villiers-sur-Marne',
    'populationTotale': 33313,
    'populationMunicipale': 33162},
   {'code': '94080',
    'siren': '219400801',
    'nom': 'Vincennes',
    'populationTotale': 48644,
    'populationMunicipale': 48193}],
  'populationTotale': 521673,
  'populationMunicipale': 517705},
 {'code': '200057966',
  'nom': 'Vallée Sud-Grand Paris',
  'type': 'EPT',
  'modeFinancement': '',
  'membres': [{'code': '92002',
    'siren': '219200029',
    'nom': 'Antony',
    'populationTotale': 65037,
    'populationMunicipale': 64263},
   {'code': '92007',
    'siren': '219200078',
    'nom': 'Bagneux',
    'populationTotale': 44744,
    'populationMunicipale': 44572},
   {'code': '92014',
    'siren': '219200144',
    'nom': 'Bourg-la-Reine',
    'populationTotale': 21318,
    'populationMunicipale': 21019},
   {'code': '92019',
    'siren': '219200193',
    'nom': 'Châtenay-Malabry',
    'populationTotale': 36275,
    'populationMunicipale': 35825},
   {'code': '92020',
    'siren': '219200201',
    'nom': 'Châtillon',
    'populationTotale': 36958,
    'populationMunicipale': 36705},
   {'code': '92023',
    'siren': '219200235',
    'nom': 'Clamart',
    'populationTotale': 59112,
    'populationMunicipale': 58576},
   {'code': '92032',
    'siren': '219200326',
    'nom': 'Fontenay-aux-Roses',
    'populationTotale': 24252,
    'populationMunicipale': 24070},
   {'code': '92046',
    'siren': '219200466',
    'nom': 'Malakoff',
    'populationTotale': 30774,
    'populationMunicipale': 30557},
   {'code': '92049',
    'siren': '219200490',
    'nom': 'Montrouge',
    'populationTotale': 46579,
    'populationMunicipale': 46324},
   {'code': '92060',
    'siren': '219200607',
    'nom': 'Le Plessis-Robinson',
    'populationTotale': 29016,
    'populationMunicipale': 28848},
   {'code': '92071',
    'siren': '219200714',
    'nom': 'Sceaux',
    'populationTotale': 21203,
    'populationMunicipale': 20884}],
  'populationTotale': 415268,
  'populationMunicipale': 411643},
 {'code': '200057974',
  'nom': 'Grand Paris Seine Ouest',
  'type': 'EPT',
  'modeFinancement': '',
  'membres': [{'code': '92012',
    'siren': '219200128',
    'nom': 'Boulogne-Billancourt',
    'populationTotale': 120206,
    'populationMunicipale': 119019},
   {'code': '92022',
    'siren': '219200227',
    'nom': 'Chaville',
    'populationTotale': 20904,
    'populationMunicipale': 20594},
   {'code': '92040',
    'siren': '219200409',
    'nom': 'Issy-les-Moulineaux',
    'populationTotale': 68449,
    'populationMunicipale': 67669},
   {'code': '92047',
    'siren': '219200474',
    'nom': 'Marnes-la-Coquette',
    'populationTotale': 1808,
    'populationMunicipale': 1752},
   {'code': '92048',
    'siren': '219200482',
    'nom': 'Meudon',
    'populationTotale': 46959,
    'populationMunicipale': 46334},
   {'code': '92072',
    'siren': '219200722',
    'nom': 'Sèvres',
    'populationTotale': 22599,
    'populationMunicipale': 22303},
   {'code': '92075',
    'siren': '219200755',
    'nom': 'Vanves',
    'populationTotale': 28858,
    'populationMunicipale': 28622},
   {'code': '92077',
    'siren': '219200771',
    'nom': "Ville-d'Avray",
    'populationTotale': 11323,
    'populationMunicipale': 11089}],
  'populationTotale': 321106,
  'populationMunicipale': 317382},
 {'code': '200057982',
  'nom': 'Paris Ouest La Défense',
  'type': 'EPT',
  'modeFinancement': '',
  'membres': [{'code': '92026',
    'siren': '219200268',
    'nom': 'Courbevoie',
    'populationTotale': 83480,
    'populationMunicipale': 82902},
   {'code': '92033',
    'siren': '219200334',
    'nom': 'Garches',
    'populationTotale': 18117,
    'populationMunicipale': 17743},
   {'code': '92035',
    'siren': '219200359',
    'nom': 'La Garenne-Colombes',
    'populationTotale': 30460,
    'populationMunicipale': 30197},
   {'code': '92044',
    'siren': '219200441',
    'nom': 'Levallois-Perret',
    'populationTotale': 68620,
    'populationMunicipale': 68092},
   {'code': '92050',
    'siren': '219200508',
    'nom': 'Nanterre',
    'populationTotale': 98383,
    'populationMunicipale': 97783},
   {'code': '92051',
    'siren': '219200516',
    'nom': 'Neuilly-sur-Seine',
    'populationTotale': 60515,
    'populationMunicipale': 59538},
   {'code': '92062',
    'siren': '219200623',
    'nom': 'Puteaux',
    'populationTotale': 44242,
    'populationMunicipale': 44002},
   {'code': '92063',
    'siren': '219200631',
    'nom': 'Rueil-Malmaison',
    'populationTotale': 84409,
    'populationMunicipale': 82874},
   {'code': '92064',
    'siren': '219200649',
    'nom': 'Saint-Cloud',
    'populationTotale': 30332,
    'populationMunicipale': 29855},
   {'code': '92073',
    'siren': '219200730',
    'nom': 'Suresnes',
    'populationTotale': 49494,
    'populationMunicipale': 48956},
   {'code': '92076',
    'siren': '219200763',
    'nom': 'Vaucresson',
    'populationTotale': 8745,
    'populationMunicipale': 8432}],
  'populationTotale': 576797,
  'populationMunicipale': 570374},
 {'code': '200057990',
  'nom': 'Boucle Nord de Seine',
  'type': 'EPT',
  'modeFinancement': '',
  'membres': [{'code': '92004',
    'siren': '219200045',
    'nom': 'Asnières-sur-Seine',
    'populationTotale': 94562,
    'populationMunicipale': 93941},
   {'code': '92009',
    'siren': '219200094',
    'nom': 'Bois-Colombes',
    'populationTotale': 29250,
    'populationMunicipale': 28909},
   {'code': '92024',
    'siren': '219200243',
    'nom': 'Clichy',
    'populationTotale': 64658,
    'populationMunicipale': 64410},
   {'code': '92025',
    'siren': '219200250',
    'nom': 'Colombes',
    'populationTotale': 91663,
    'populationMunicipale': 91053},
   {'code': '92036',
    'siren': '219200367',
    'nom': 'Gennevilliers',
    'populationTotale': 51177,
    'populationMunicipale': 50979},
   {'code': '92078',
    'siren': '219200789',
    'nom': 'Villeneuve-la-Garenne',
    'populationTotale': 26094,
    'populationMunicipale': 26021},
   {'code': '95018',
    'siren': '219500188',
    'nom': 'Argenteuil',
    'populationTotale': 106546,
    'populationMunicipale': 106130}],
  'populationTotale': 463950,
  'populationMunicipale': 461443},
 {'code': '200058006',
  'nom': 'Grand Paris Sud Est Avenir',
  'type': 'EPT',
  'modeFinancement': '',
  'membres': [{'code': '94002',
    'siren': '219400025',
    'nom': 'Alfortville',
    'populationTotale': 45702,
    'populationMunicipale': 45531},
   {'code': '94004',
    'siren': '219400041',
    'nom': 'Boissy-Saint-Léger',
    'populationTotale': 17369,
    'populationMunicipale': 17325},
   {'code': '94011',
    'siren': '219400116',
    'nom': 'Bonneuil-sur-Marne',
    'populationTotale': 18349,
    'populationMunicipale': 18270},
   {'code': '94019',
    'siren': '219400199',
    'nom': 'Chennevières-sur-Marne',
    'populationTotale': 18815,
    'populationMunicipale': 18710},
   {'code': '94028',
    'siren': '219400280',
    'nom': 'Créteil',
    'populationTotale': 93813,
    'populationMunicipale': 93397},
   {'code': '94044',
    'siren': '219400447',
    'nom': 'Limeil-Brévannes',
    'populationTotale': 27512,
    'populationMunicipale': 27406},
   {'code': '94047',
    'siren': '219400470',
    'nom': 'Mandres-les-Roses',
    'populationTotale': 4972,
    'populationMunicipale': 4922},
   {'code': '94048',
    'siren': '219400488',
    'nom': 'Marolles-en-Brie',
    'populationTotale': 4903,
    'populationMunicipale': 4781},
   {'code': '94053',
    'siren': '219400538',
    'nom': 'Noiseau',
    'populationTotale': 4671,
    'populationMunicipale': 4628},
   {'code': '94055',
    'siren': '219400553',
    'nom': 'Ormesson-sur-Marne',
    'populationTotale': 11053,
    'populationMunicipale': 10977},
   {'code': '94056',
    'siren': '219400561',
    'nom': 'Périgny',
    'populationTotale': 2757,
    'populationMunicipale': 2724},
   {'code': '94059',
    'siren': '219400595',
    'nom': 'Le Plessis-Trévise',
    'populationTotale': 21237,
    'populationMunicipale': 21112},
   {'code': '94060',
    'siren': '219400603',
    'nom': 'La Queue-en-Brie',
    'populationTotale': 12353,
    'populationMunicipale': 12241},
   {'code': '94070',
    'siren': '219400702',
    'nom': 'Santeny',
    'populationTotale': 3963,
    'populationMunicipale': 3913},
   {'code': '94071',
    'siren': '219400710',
    'nom': 'Sucy-en-Brie',
    'populationTotale': 28016,
    'populationMunicipale': 27764},
   {'code': '94075',
    'siren': '219400751',
    'nom': 'Villecresnes',
    'populationTotale': 11747,
    'populationMunicipale': 11647}],
  'populationTotale': 327232,
  'populationMunicipale': 325348},
 {'code': '200058014',
  'nom': 'Grand-Orly Seine Bièvre',
  'type': 'EPT',
  'modeFinancement': '',
  'membres': [{'code': '91027',
    'siren': '219100278',
    'nom': 'Athis-Mons',
    'populationTotale': 36899,
    'populationMunicipale': 36613},
   {'code': '91326',
    'siren': '219103264',
    'nom': 'Juvisy-sur-Orge',
    'populationTotale': 19375,
    'populationMunicipale': 19292},
   {'code': '91432',
    'siren': '219104320',
    'nom': 'Morangis',
    'populationTotale': 14196,
    'populationMunicipale': 14129},
   {'code': '91479',
    'siren': '219104791',
    'nom': 'Paray-Vieille-Poste',
    'populationTotale': 8246,
    'populationMunicipale': 8202},
   {'code': '91589',
    'siren': '219105897',
    'nom': 'Savigny-sur-Orge',
    'populationTotale': 37876,
    'populationMunicipale': 37601},
   {'code': '91687',
    'siren': '219106879',
    'nom': 'Viry-Châtillon',
    'populationTotale': 31012,
    'populationMunicipale': 30838},
   {'code': '94001',
    'siren': '219400017',
    'nom': 'Ablon-sur-Seine',
    'populationTotale': 6025,
    'populationMunicipale': 5988},
   {'code': '94003',
    'siren': '219400033',
    'nom': 'Arcueil',
    'populationTotale': 22306,
    'populationMunicipale': 22200},
   {'code': '94016',
    'siren': '219400165',
    'nom': 'Cachan',
    'populationTotale': 31434,
    'populationMunicipale': 31103},
   {'code': '94021',
    'siren': '219400215',
    'nom': 'Chevilly-Larue',
    'populationTotale': 19900,
    'populationMunicipale': 19826},
   {'code': '94022',
    'siren': '219400223',
    'nom': 'Choisy-le-Roi',
    'populationTotale': 46126,
    'populationMunicipale': 45946},
   {'code': '94034',
    'siren': '219400348',
    'nom': 'Fresnes',
    'populationTotale': 29644,
    'populationMunicipale': 29528},
   {'code': '94037',
    'siren': '219400371',
    'nom': 'Gentilly',
    'populationTotale': 20062,
    'populationMunicipale': 19963},
   {'code': '94038',
    'siren': '219400389',
    'nom': "L'Haÿ-les-Roses",
    'populationTotale': 31394,
    'populationMunicipale': 31188},
   {'code': '94041',
    'siren': '219400413',
    'nom': 'Ivry-sur-Seine',
    'populationTotale': 65263,
    'populationMunicipale': 65064},
   {'code': '94043',
    'siren': '219400439',
    'nom': 'Le Kremlin-Bicêtre',
    'populationTotale': 24206,
    'populationMunicipale': 24110},
   {'code': '94054',
    'siren': '219400546',
    'nom': 'Orly',
    'populationTotale': 24853,
    'populationMunicipale': 24658},
   {'code': '94065',
    'siren': '219400652',
    'nom': 'Rungis',
    'populationTotale': 5662,
    'populationMunicipale': 5611},
   {'code': '94073',
    'siren': '219400736',
    'nom': 'Thiais',
    'populationTotale': 33141,
    'populationMunicipale': 32918},
   {'code': '94074',
    'siren': '219400744',
    'nom': 'Valenton',
    'populationTotale': 14444,
    'populationMunicipale': 14406},
   {'code': '94076',
    'siren': '219400769',
    'nom': 'Villejuif',
    'populationTotale': 60473,
    'populationMunicipale': 60183},
   {'code': '94077',
    'siren': '219400777',
    'nom': 'Villeneuve-le-Roi',
    'populationTotale': 21062,
    'populationMunicipale': 21000},
   {'code': '94078',
    'siren': '219400785',
    'nom': 'Villeneuve-Saint-Georges',
    'populationTotale': 36319,
    'populationMunicipale': 36221},
   {'code': '94081',
    'siren': '219400819',
    'nom': 'Vitry-sur-Seine',
    'populationTotale': 94393,
    'populationMunicipale': 93963}],
  'populationTotale': 734311,
  'populationMunicipale': 730551},
 {'code': '200058097',
  'nom': "Paris Terres d'Envol",
  'type': 'EPT',
  'modeFinancement': '',
  'membres': [{'code': '93005',
    'siren': '219300050',
    'nom': 'Aulnay-sous-Bois',
    'populationTotale': 87951,
    'populationMunicipale': 87599},
   {'code': '93007',
    'siren': '219300076',
    'nom': 'Le Blanc-Mesnil',
    'populationTotale': 62547,
    'populationMunicipale': 62376},
   {'code': '93013',
    'siren': '219300134',
    'nom': 'Le Bourget',
    'populationTotale': 15970,
    'populationMunicipale': 15925},
   {'code': '93029',
    'siren': '219300290',
    'nom': 'Drancy',
    'populationTotale': 72583,
    'populationMunicipale': 72390},
   {'code': '93030',
    'siren': '219300308',
    'nom': 'Dugny',
    'populationTotale': 11728,
    'populationMunicipale': 11700},
   {'code': '93071',
    'siren': '219300712',
    'nom': 'Sevran',
    'populationTotale': 52682,
    'populationMunicipale': 52535},
   {'code': '93073',
    'siren': '219300738',
    'nom': 'Tremblay-en-France',
    'populationTotale': 38519,
    'populationMunicipale': 38348},
   {'code': '93078',
    'siren': '219300787',
    'nom': 'Villepinte',
    'populationTotale': 41579,
    'populationMunicipale': 41470}],
  'populationTotale': 383559,
  'populationMunicipale': 382343},
 {'code': '200058790',
  'nom': 'Grand Paris Grand Est',
  'type': 'EPT',
  'modeFinancement': '',
  'membres': [{'code': '93014',
    'siren': '219300142',
    'nom': 'Clichy-sous-Bois',
    'populationTotale': 29421,
    'populationMunicipale': 29354},
   {'code': '93015',
    'siren': '219300159',
    'nom': 'Coubron',
    'populationTotale': 5217,
    'populationMunicipale': 5175},
   {'code': '93032',
    'siren': '219300324',
    'nom': 'Gagny',
    'populationTotale': 42524,
    'populationMunicipale': 42313},
   {'code': '93033',
    'siren': '219300332',
    'nom': 'Gournay-sur-Marne',
    'populationTotale': 7362,
    'populationMunicipale': 7320},
   {'code': '93046',
    'siren': '219300464',
    'nom': 'Livry-Gargan',
    'populationTotale': 47453,
    'populationMunicipale': 47228},
   {'code': '93047',
    'siren': '219300472',
    'nom': 'Montfermeil',
    'populationTotale': 28825,
    'populationMunicipale': 28703},
   {'code': '93049',
    'siren': '219300498',
    'nom': 'Neuilly-Plaisance',
    'populationTotale': 22063,
    'populationMunicipale': 21941},
   {'code': '93050',
    'siren': '219300506',
    'nom': 'Neuilly-sur-Marne',
    'populationTotale': 39891,
    'populationMunicipale': 39800},
   {'code': '93051',
    'siren': '219300514',
    'nom': 'Noisy-le-Grand',
    'populationTotale': 73408,
    'populationMunicipale': 72978},
   {'code': '93057',
    'siren': '219300571',
    'nom': 'Les Pavillons-sous-Bois',
    'populationTotale': 25875,
    'populationMunicipale': 25804},
   {'code': '93062',
    'siren': '219300621',
    'nom': 'Le Raincy',
    'populationTotale': 14920,
    'populationMunicipale': 14735},
   {'code': '93064',
    'siren': '219300647',
    'nom': 'Rosny-sous-Bois',
    'populationTotale': 47368,
    'populationMunicipale': 47180},
   {'code': '93074',
    'siren': '219300746',
    'nom': 'Vaujours',
    'populationTotale': 8040,
    'populationMunicipale': 8007},
   {'code': '93077',
    'siren': '219300779',

In [8]:
df_ept = pd.json_normalize(
    data_ept,
    record_path="membres",
    meta=[
        "code",
        "nom",
        "type",
        "modeFinancement",
        "populationTotale",
        "populationMunicipale"
    ],
    record_prefix="",
    meta_prefix="epci_"
)

In [9]:
df_ept

,code,siren,nom,populationTotale,populationMunicipale,epci_code,epci_nom,epci_type,epci_modeFinancement,epci_populationTotale,epci_populationMunicipale
0,93001,219300019,Aubervilliers,88529,88365,200057867,Plaine Commune,EPT,,455226,453671
1,93027,219300274,La Courneuve,47285,47167,200057867,Plaine Commune,EPT,,455226,453671
2,93031,219300316,Épinay-sur-Seine,52944,52833,200057867,Plaine Commune,EPT,,455226,453671
3,93039,219300399,L'Île-Saint-Denis,8715,8696,200057867,Plaine Commune,EPT,,455226,453671
4,93066,NaN,Saint-Denis,149936,149077,200057867,Plaine Commune,EPT,,455226,453671
...,...,...,...,...,...,...,...,...,...,...,...
124,93057,219300571,Les Pavillons-sous-Bois,25875,25804,200058790,Grand Paris Grand Est,EPT,,422336,420333
125,93062,219300621,Le Raincy,14920,14735,200058790,Grand Paris Grand Est,EPT,,422336,420333
126,93064,219300647,Rosny-sous-Bois,47368,47180,200058790,Grand Paris Grand Est,EPT,,422336,420333
127,93074,219300746,Vaujours,8040,8007,200058790,Grand Paris Grand Est,EPT,,422336,420333
128,93077,219300779,Villemomble,29969,29795,200058790,Grand Paris Grand Est,EPT,,422336,420333

In [10]:
df_ept['epci_code'].unique()

array(['200057867', '200057875', '200057941', '200057966', '200057974',
       '200057982', '200057990', '200058006', '200058014', '200058097',
       '200058790'], dtype=object)

In [11]:
df_total = pd.concat([df, df_ept], ignore_index=True)

In [12]:
df_total

,code,siren,nom,populationTotale,populationMunicipale,epci_code,epci_nom,epci_type,epci_modeFinancement,epci_populationTotale,epci_populationMunicipale
0,74042,217400423,Bonneville,13736,13320,200000172,CC Faucigny - Glières,CC,FPU,29204,28363
1,74164,217401645,Marignier,6612,6432,200000172,CC Faucigny - Glières,CC,FPU,29204,28363
2,74087,217400878,Contamine-sur-Arve,2498,2374,200000172,CC Faucigny - Glières,CC,FPU,29204,28363
3,74024,217400241,Ayse,2372,2325,200000172,CC Faucigny - Glières,CC,FPU,29204,28363
4,74212,200081446,Glières-Val-de-Borne,1863,1825,200000172,CC Faucigny - Glières,CC,FPU,29204,28363
...,...,...,...,...,...,...,...,...,...,...,...
34995,93057,219300571,Les Pavillons-sous-Bois,25875,25804,200058790,Grand Paris Grand Est,EPT,,422336,420333
34996,93062,219300621,Le Raincy,14920,14735,200058790,Grand Paris Grand Est,EPT,,422336,420333
34997,93064,219300647,Rosny-sous-Bois,47368,47180,200058790,Grand Paris Grand Est,EPT,,422336,420333
34998,93074,219300746,Vaujours,8040,8007,200058790,Grand Paris Grand Est,EPT,,422336,420333
34999,93077,219300779,Villemomble,29969,29795,200058790,Grand Paris Grand Est,EPT,,422336,420333

In [13]:
df_total['code'] = df_total['code'].astype(str)

In [14]:
df_com = pd.read_csv("../data/raw/communes_france_2025.csv", sep = ",")

/tmp/ipykernel_3949/3012244801.py:1: DtypeWarning: Columns (1,12,14,16,23,24) have mixed types. Specify dtype option on import or set low_memory=False.
  df_com = pd.read_csv("../data/raw/communes_france_2025.csv", sep = ",")

In [15]:
df_com['code_insee'] = df_com['code_insee'].astype(str)

In [16]:
df_com

,Unnamed: 0,code_insee,nom_standard,nom_sans_pronom,nom_a,nom_de,nom_sans_accent,nom_standard_majuscule,typecom,typecom_texte,...,longitude_mairie,latitude_centre,longitude_centre,grille_densite,grille_densite_texte,niveau_equipements_services,niveau_equipements_services_texte,gentile,url_wikipedia,url_villedereve
0,0,01001,L'Abergement-Clémenciat,Abergement-Clémenciat,à Abergement-Clémenciat,de l'Abergement-Clémenciat,l-abergement-clemenciat,L'ABERGEMENT-CLÉMENCIAT,COM,commune,...,4.921,46.153,4.926,6,Rural à habitat dispersé,0.0,communes non pôle,NaN,https://fr.wikipedia.org/wiki/fr:L'Abergement-...,https://villedereve.fr/ville/01001-l-abergemen...
1,1,01002,L'Abergement-de-Varey,Abergement-de-Varey,à Abergement-de-Varey,de l'Abergement-de-Varey,l-abergement-de-varey,L'ABERGEMENT-DE-VAREY,COM,commune,...,5.423,46.009,5.428,6,Rural à habitat dispersé,0.0,communes non pôle,"Abergementais, Abergementaises",https://fr.wikipedia.org/wiki/fr:L'Abergement-...,https://villedereve.fr/ville/01002-l-abergemen...
2,2,01004,Ambérieu-en-Bugey,Ambérieu-en-Bugey,à Ambérieu-en-Bugey,d'Ambérieu-en-Bugey,amberieu-en-bugey,AMBÉRIEU-EN-BUGEY,COM,commune,...,5.360,45.961,5.373,2,Centres urbains intermédiaires,3.0,centres structurants d'équipements et de services,"Ambarrois, Ambarroises",https://fr.wikipedia.org/wiki/fr:Ambérieu-en-B...,https://villedereve.fr/ville/01004-amberieu-en...
3,3,01005,Ambérieux-en-Dombes,Ambérieux-en-Dombes,à Ambérieux-en-Dombes,d'Ambérieux-en-Dombes,amberieux-en-dombes,AMBÉRIEUX-EN-DOMBES,COM,commune,...,4.903,45.996,4.912,5,Bourgs ruraux,1.0,centres locaux d'équipements et de services,Ambarrois,https://fr.wikipedia.org/wiki/fr:Ambérieux-en-...,https://villedereve.fr/ville/01005-amberieux-e...
4,4,01006,Ambléon,Ambléon,à Ambléon,d'Ambléon,ambleon,AMBLÉON,COM,commune,...,5.601,45.750,5.594,6,Rural à habitat dispersé,0.0,communes non pôle,Ambléonais,https://fr.wikipedia.org/wiki/fr:Ambléon,https://villedereve.fr/ville/01006-ambleon
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34930,34930,97613,M'Tsangamouji,M'Tsangamouji,à M'Tsangamouji,de M'Tsangamouji,m-tsangamouji,M'TSANGAMOUJI,COM,commune,...,45.084,-12.751,45.087,3,Petites villes,NaN,NaN,NaN,https://fr.wikipedia.org/wiki/fr:M'Tsangamouji,https://villedereve.fr/ville/97613-m-tsangamouji
34931,34931,97614,Ouangani,Ouangani,à Ouangani,d'Ouangani,ouangani,OUANGANI,COM,commune,...,45.139,-12.837,45.138,3,Petites villes,NaN,NaN,NaN,https://fr.wikipedia.org/wiki/fr:Ouangani,https://villedereve.fr/ville/97614-ouangani
34932,34932,97615,Pamandzi,Pamandzi,à Pamandzi,de Pamandzi,pamandzi,PAMANDZI,COM,commune,...,45.275,-12.796,45.284,2,Centres urbains intermédiaires,NaN,NaN,Pamandziens,https://fr.wikipedia.org/wiki/fr:Pamandzi,https://villedereve.fr/ville/97615-pamandzi
34933,34933,97616,Sada,Sada,à Sada,de Sada,sada,SADA,COM,commune,...,45.106,-12.861,45.119,2,Centres urbains intermédiaires,NaN,NaN,Sadois,https://fr.wikipedia.org/wiki/fr:Sada (Mayotte),https://villedereve.fr/ville/97616-sada
34934,34934,97617,Tsingoni,Tsingoni,à Tsingoni,de Tsingoni,tsingoni,TSINGONI,COM,commune,...,45.105,-12.782,45.134,2,Centres urbains intermédiaires,NaN,NaN,NaN,https://fr.wikipedia.org/wiki/fr:Tsingoni,https://villedereve.fr/ville/97617-tsingoni

In [17]:
df_total = df_total.merge(
    df_com[["code_insee", "superficie_hectare", "superficie_km2"]],
    left_on="code",
    right_on="code_insee",
    how="left"
)

In [18]:
df_total = df_total.drop(columns=["code_insee"])

In [19]:
df_total['dept'] = df_total['code'].str[:2]

In [20]:
df_bassin_vie = pd.read_csv("../data/raw/bassin_vie.csv", sep = ";")

In [21]:
df_bassin_vie

      code_insee bassin_vie
0          01001      01093
1          01002      01004
2          01004      01004
3          01005      01333
4          01006      01034
...          ...        ...
34870      97613      97611
34871      97614      97611
34872      97615      97608
34873      97616      97611
34874      97617      97611

[34875 rows x 2 columns]

In [22]:
df_total = df_total.merge(
    df_bassin_vie[["code_insee", "bassin_vie"]],
    left_on="code",
    right_on="code_insee",
    how="left").drop(columns=["code_insee"])

In [23]:
df_total.columns

Index(['code', 'siren', 'nom', 'populationTotale', 'populationMunicipale',
       'epci_code', 'epci_nom', 'epci_type', 'epci_modeFinancement',
       'epci_populationTotale', 'epci_populationMunicipale',
       'superficie_hectare', 'superficie_km2', 'dept', 'bassin_vie'],
      dtype='object')

In [24]:
df_total.drop(columns=["siren"], inplace=True)

In [25]:
mapping = { 
    "code": "code_insee",
    'populationTotale': 'pop_tot_commune',
    'populationMunicipale': 'pop_mun_commune',
    'epci_populationTotale': 'total_pop_tot',
    'epci_populationMunicipale': 'total_pop_mun',
    'epci_code': 'siren',
}

df_total.rename(columns=mapping,inplace=True)

In [26]:
df_total = df_total.sort_values(by=['dept','siren']).reset_index(drop=True)

In [27]:
df_total[(df_total['epci_type']=='EPT') & (df_total['nom'].str.startswith('Paris'))]

Empty DataFrame
Columns: [code_insee, nom, pop_tot_commune, pop_mun_commune, siren, epci_nom, epci_type, epci_modeFinancement, total_pop_tot, total_pop_mun, superficie_hectare, superficie_km2, dept, bassin_vie]
Index: []

In [28]:
df_paris = df_total[df_total['code_insee']=='75056']

In [29]:
#modifier le siren de df_paris
df_paris.loc[:, 'siren'] = '75056'
df_paris.loc[:, 'epci_nom'] = 'Paris'
df_paris.loc[:, 'epci_type'] = 'Commune'
df_paris.loc[:, 'total_pop_tot'] = df_paris.loc[:, 'pop_tot_commune']
df_paris.loc[:, 'total_pop_mun'] = df_paris.loc[:, 'pop_mun_commune']

In [30]:
df_paris

,code_insee,nom,pop_tot_commune,pop_mun_commune,siren,epci_nom,epci_type,epci_modeFinancement,total_pop_tot,total_pop_mun,superficie_hectare,superficie_km2,dept,bassin_vie
29191,75056,Paris,2129257,2113705,75056,Paris,Commune,FPU,2129257,2113705,10540.0,105.0,75,75056

In [31]:
df_epci = pd.read_csv("../data/data_asso/raw/data_epci.csv",sep=";", encoding='latin1',dtype = str)

In [32]:
df_epci

,dept,siren,raison_sociale,nature_juridique,mode_financ,nb_membres,total_pop_tot,total_pop_mun,dep_com,insee,siren_membre,nom_membre,ptot_2025,pmun_2025
0,01,200029999,CC Rives de l'Ain - Pays du Cerdon,CC,FPU,14,15 156,14 873,01,01304,210103040,Pont-d'Ain,2 912,2 862
1,01,200029999,CC Rives de l'Ain - Pays du Cerdon,CC,FPU,14,15 156,14 873,01,01199,210101994,Jujurieux,2 246,2 209
2,01,200029999,CC Rives de l'Ain - Pays du Cerdon,CC,FPU,14,15 156,14 873,01,01363,210103636,Saint-Jean-le-Vieux,1 873,1 799
3,01,200029999,CC Rives de l'Ain - Pays du Cerdon,CC,FPU,14,15 156,14 873,01,01314,210103149,Priay,1 826,1 803
4,01,200029999,CC Rives de l'Ain - Pays du Cerdon,CC,FPU,14,15 156,14 873,01,01273,210102737,Neuville-sur-Ain,1 823,1 798
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34867,2B,242020105,CC de Calvi Balagne,CC,FPU,14,12 842,12 638,2B,2B138,212001382,Lavatoggio,158,156
34868,2B,242020105,CC de Calvi Balagne,CC,FPU,14,12 842,12 638,2B,2B296,212002968,Sant'Antonino,133,132
34869,2B,242020105,CC de Calvi Balagne,CC,FPU,14,12 842,12 638,2B,2B153,212001531,Manso,120,117
34870,2B,242020105,CC de Calvi Balagne,CC,FPU,14,12 842,12 638,2B,2B025,212000251,Avapessa,81,81
34871,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
query = """ 
SELECT 
DISTINCT siren,
dept
FROM df_epci
"""

df_epci_filtered = duckdb.query(query)

In [39]:
df_ept_filtered = df_ept[['epci_code', 'epci_nom']].drop_duplicates()

In [40]:
df_ept_filtered

     epci_code                    epci_nom
0    200057867              Plaine Commune
8    200057875                Est Ensemble
17   200057941     Paris Est Marne et Bois
30   200057966      Vallée Sud-Grand Paris
41   200057974     Grand Paris Seine Ouest
49   200057982      Paris Ouest La Défense
60   200057990        Boucle Nord de Seine
67   200058006  Grand Paris Sud Est Avenir
83   200058014     Grand-Orly Seine Bièvre
107  200058097        Paris Terres d'Envol
115  200058790       Grand Paris Grand Est

In [46]:
dict_ept = {
    200057941:94,
    200057875: 93,
    200057867: 93,
    200057990: 92,
    200057982: 92,
    200057974: 92,
    200058006: 94,
    200057966: 92,
    200058790: 93,
    200058014: 94,
    200058097: 93,
    75056: 75
}

df_ept_corres = pd.DataFrame(list(dict_ept.items()), columns=['siren', 'dept'])

In [47]:
df_correpondance = pd.concat([df_epci_filtered.df(), df_ept_corres], ignore_index=True)

In [48]:
df_correpondance

          siren dept
0     200042935   01
1     200069193   01
2     240100610   01
3     240100750   01
4     240100800   01
...         ...  ...
1263  200057966   92
1264  200058790   93
1265  200058014   94
1266  200058097   93
1267      75056   75

[1268 rows x 2 columns]

In [51]:
query = """
SELECT 
    df_total.*,
    df_correpondance.dept AS dept_epci
FROM df_total
LEFT JOIN df_correpondance
ON df_total.siren = df_correpondance.siren
"""

df_total = duckdb.query(query).to_df()

In [54]:
df_total = df_total.drop(columns=['dept_id'])

In [55]:
df_total.rename(columns={'dept':'dept_com'}, inplace=True)

In [56]:
df_total = df_total.sort_values(by=['dept_epci','siren']).reset_index(drop=True)

In [59]:
df_total['dept_epci'].unique()

array(['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11',
       '12', '13', '14', '15', '16', '17', '18', '19', '21', '22', '23',
       '24', '25', '26', '27', '28', '29', '2A', '2B', '30', '31', '32',
       '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43',
       '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54',
       '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65',
       '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76',
       '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87',
       '88', '89', '90', '91', '92', '93', '94', '95', '971', '972',
       '973', '974', '976'], dtype=object)

In [60]:
df_total['dept_com'].unique()

array(['01', '02', '03', '58', '04', '83', '05', '26', '06', '07', '08',
       '09', '10', '11', '12', '46', '48', '13', '84', '14', '27', '15',
       '16', '17', '18', '19', '23', '21', '71', '22', '24', '25', '76',
       '28', '29', '2A', '2B', '30', '31', '81', '32', '33', '34', '35',
       '44', '56', '36', '37', '38', '73', '69', '39', '40', '41', '42',
       '43', '49', '45', '89', '47', '50', '51', '52', '70', '53', '54',
       '55', '57', '88', '67', '59', '62', '60', '61', '72', '80', '63',
       '64', '65', '66', '68', '74', '75', '91', '92', '93', '94', '95',
       '77', '78', '79', '82', '85', '86', '87', '90', '97'], dtype=object)

In [57]:
df_total

,code_insee,nom,pop_tot_commune,pop_mun_commune,siren,epci_nom,epci_type,epci_modeFinancement,total_pop_tot,total_pop_mun,superficie_hectare,superficie_km2,dept_com,bassin_vie,dept_epci
0,01304,Pont-d'Ain,2912,2862,200029999,CC Rives de l'Ain - Pays du Cerdon,CC,FPU,15156,14873,1122.0,11.0,01,01304,01
1,01199,Jujurieux,2246,2209,200029999,CC Rives de l'Ain - Pays du Cerdon,CC,FPU,15156,14873,1548.0,15.0,01,01004,01
2,01363,Saint-Jean-le-Vieux,1873,1799,200029999,CC Rives de l'Ain - Pays du Cerdon,CC,FPU,15156,14873,1517.0,15.0,01,01004,01
3,01314,Priay,1826,1803,200029999,CC Rives de l'Ain - Pays du Cerdon,CC,FPU,15156,14873,1571.0,16.0,01,01004,01
4,01273,Neuville-sur-Ain,1823,1798,200029999,CC Rives de l'Ain - Pays du Cerdon,CC,FPU,15156,14873,1991.0,20.0,01,01004,01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34996,97601,Acoua,5384,5192,200060465,CA du Grand Nord de Mayotte,CA,FPU,60372,59042,1290.0,13.0,97,97611,976
34997,97603,Bandrele,10529,10282,200060473,CC du Sud,CC,FPU,31945,30898,3514.0,35.0,97,97611,976
34998,97606,Chirongui,9197,8920,200060473,CC du Sud,CC,FPU,31945,30898,2590.0,26.0,97,97611,976
34999,97604,Bouéni,6503,6189,200060473,CC du Sud,CC,FPU,31945,30898,1381.0,14.0,97,97611,976
35000,97609,Kani-Kéli,5716,5507,200060473,CC du Sud,CC,FPU,31945,30898,2004.0,20.0,97,97611,976

In [58]:
df_total.to_csv("../data/processed/epci_membres.csv", index=False)